server:
  port: 8081

spring:
  application:
    name: CATALOG-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog_db
    username: root
    password: Root@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

get:
  store:
    url: http://STORE-SERVICE/store/

